# general configuration
url: https://laszlokiss.dev/
baseurl: ''

# compass configuration
compass:
  logo: "/images/me.jpg"
  author: "László Kiss"
  tagline: "Software Developer"
  include_content: true
  include_analytics: false
  github: "lszlkss"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", ".gitignore"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
